require 'rubygems'
require 'rake'
require 'echoe'

Echoe.new('socketlabs', '0.1.0') do |p|
  p.description    = "Send email through SocketLabs."
  p.url            = "http://github.com/socketlabs/socketlabs"
  p.author         = "Author Name"
  p.email          = "email@example.com "
  p.ignore_pattern = ["tmp/*", "script/*"]
  p.development_dependencies = []
end

Dir["#{File.dirname(__FILE__)}/tasks/*.rake"].sort.each { |ext| load ext }
